name: Front Deployment 

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-northeast-2

# 위의 이벤트가 트리거되면 실행할 목록입니다.
jobs:
  build:
    name: react build & deploy
    # runner가 실행될 환경을 지정합니다.
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      
      - name: Check Node v
        run: node -v
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy
      
      - name: zip create
        run: zip -qq -r ./build.zip .
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Upload to S3
        run: aws s3 cp ./build.zip s3://${{ secrets.S3_BUCKET_NAME }}/front/$GITHUB_SHA.zip --region ${{ env.AWS_REGION }}
    
      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ secrets.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=front/$GITHUB_SHA.zip,bundleType=zip
        env:
          AWS_REGION: ap-northeast-2
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID  }}
