name: Frontend Deployment

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-northeast-2

# 아래의 이벤트가 트리거되면 실행할 목록입니다.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 코드 체크아웃
        uses: actions/checkout@v3

      - name: Configure AWS IAM user # AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build React app # 리액트 빌드
        run: |
          npm install
          npm run build

      - name: Upload built files to S3 # 빌드한 파일 S3에 업로드
        run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront cache # CloudFront 캐시 무력화 설정
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}